LexiconLMS/LexiconLMS/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LexiconLMS.Models
{
    public class Group
    {
        //[Key, ForeignKey("Schedule")]
        [Key]
        public int Id { get; set; }
        public string GroupName { get; set; }
        public int ScheduleId { get; set; }
        [ForeignKey("ScheduleId")]
        public virtual Schedule schedule { get; set; }

        public virtual ICollection<ApplicationUser> Users { get; set; }

    }
}

LexiconLMS/LexiconLMS/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LexiconLMS.Models;
using LexiconLMS.ViewModels;

namespace LexiconLMS.Controllers
{
    public class GroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Groups
        public ActionResult Index()
        {
            var groups = db.Groups.Include(g => g.schedule);
            return View(groups.ToList());
        }

        // GET: Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }

            List<GroupUsersViewModels> GUVM = new List<GroupUsersViewModels>();


            //var us = db.Users.Single(u => u.Id == id);
            //foreach (ApplicationUser user in db.Users.Single(db.Groups.Single(g => g.Id == group.Id)))
            List<ApplicationUser> UG = group.Users.ToList();

            //foreach (var u in group.Users)
            //{
            //    try
            //    {
            //        if (u.Groups != null && u.Groups.Count > 0)
            //        {
            //            foreach (var g in u.Groups)
            //            {
            //                if (g.Id == group.Id)
            //                {
            //                    UG.Add(u);
            //                }
            //            }
            //        }
            //    }
                //catch (System.Data.Entity.Core.EntityCommandExecutionException)
                //{

                //    //UG = db.Users.Where(us => us.Groups.FirstOrDefault().Id == group.Id);
                //}
               
            //}
            //foreach (ApplicationUser user in GInfo.Where(u => u.Groups.FirstOrDefault().Id == group.Id))
            foreach (ApplicationUser user in UG)
            {
                GUVM.Add(
                    new ViewModels.GroupUsersViewModels
                    {
                        auId = user.Id,
                        Fname = user.FName,
                        Lname = user.LName,
                        Email = user.Email,
                        GroupName = group.GroupName,
                        Id = group.Id,
                        UserName = user.UserName
                    }
                );
            }
            ViewBag.GId = group.Id;
            ViewBag.GName = group.GroupName;
            return View(GUVM);
        }

        // GET: Groups/Details/5
         [HttpPost]
        public ActionResult Details(int? id, string[] Select)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }

            if (Select != null && Select.Length > 0)
            {
                
                foreach (string cId in Select)
                {
                    if (Select.FirstOrDefault().Equals("on"))
                    {
                        ViewBag.SelectError = "Something went wrong, try again";
                        break;
                    }
   
                    var us = group.Users.Single(u => u.Id.Equals(cId));
                    group.Users.Remove(us);
                    db.Groups.Find(id).Users.Remove(us);
                    //Gör dessa ändringar i db.groups :)
                }
            }
            db.SaveChanges();
            group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            List<GroupUsersViewModels> GUVM = new List<GroupUsersViewModels>();
            List<ApplicationUser> UG = group.Users.ToList();

             //foreach (ApplicationUser user in GInfo.Where(u => u.Groups.FirstOrDefault().Id == group.Id))
            foreach (ApplicationUser user in UG)
            {
                GUVM.Add(
                    new ViewModels.GroupUsersViewModels
                    {
                        Fname = user.FName,
                        Lname = user.LName,
                        Email = user.Email,
                        GroupName = group.GroupName,
                        Id = group.Id,
                        UserName = user.UserName

                    }
                );
            }
            ViewBag.GId = group.Id;
            ViewBag.GName = group.GroupName;
            return View(GUVM);
        }


        // GET: Groups/Create
        public ActionResult Create()
        {
            ViewBag.ScheduleId = new SelectList(db.Schedules, "Id", "Name");
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,GroupName,ScheduleId")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ScheduleId = new SelectList(db.Schedules, "Id", "Name", group.ScheduleId);
            return View(group);
        }

        // GET: Groups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            ViewBag.ScheduleId = new SelectList(db.Schedules, "Id", "Name", group.ScheduleId);
            return View(group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,GroupName,ScheduleId")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ScheduleId = new SelectList(db.Schedules, "Id", "Name", group.ScheduleId);
            return View(group);
        }

        // GET: Groups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Groups.Find(id);
            db.Groups.Remove(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult AddUser(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            //List<ApplicationUser> UG = db.Users.ToList();
            //foreach (ApplicationUser au in db.Users)
            //{
            //    foreach (Group g in au.Groups)
            //    {

            //        if (g.Id == group.Id)
            //            UG.RemoveAll(u => u.Id == au.Id);
            //    }
            //}
            
            var Groupinfo = db.Users.Where(u => u.Groups.All(g => g.Id != group.Id));
            ViewBag.GId = group.Id;
            return View(Groupinfo);
        }

        [HttpPost]
        public ActionResult AddUser(int? id, string[] Select)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }

            
            if (Select != null && Select.Length > 0)
            {
                foreach (string cId in Select)
                {
                    var us = db.Users.Single(u => u.Id.Equals(cId));
                    group.Users.Add(us);
                    db.Groups.Find(id).Users.Add(us);
                }
            }
            db.SaveChanges();
            group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            

LexiconLMS/LexiconLMS/Views/Groups/AddUser.cshtml
@model IEnumerable<LexiconLMS.Models.ApplicationUser>

@{
    ViewBag.Title = "AddUser";
}

<h2>AddUser</h2>
@{int groupId = ViewBag.GId;}
<p>
    @Html.ActionLink("Create New", "Register","Account",null, null)
</p>
@using (Html.BeginForm()) { 
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            Add
        </th>
    </tr>


@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            <input type="checkbox" name="Select" value=@item.Id />
        </td>
    </tr>
}
    
</table>
<input type="submit" value="Add theese users"/>
    
    
}
@Html.ActionLink("Back to Details", "Details/" + @groupId, "Groups", null, null)

LexiconLMS/LexiconLMS/Views/Groups/Create.cshtml
@model LexiconLMS.Models.Group

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>

    <div class="form-group">
                @Html.LabelFor(model => model.ScheduleId, "ScheduleId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ScheduleId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ScheduleId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>

        
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

LexiconLMS/LexiconLMS/Views/Groups/Delete.cshtml
@model LexiconLMS.Models.Group

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.schedule.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.schedule.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LexiconLMS/LexiconLMS/Views/Groups/Details.cshtml
@model IEnumerable<LexiconLMS.ViewModels.GroupUsersViewModels>

@{
    ViewBag.Title = "Details";
}

@{var aitem = Model.FirstOrDefault();}
<h2>@ViewBag.GName</h2>
@if (ViewBag.SelectError != null)
{
    <h3>@ViewBag.SelectError</h3>
}
@{int groupId = ViewBag.GId;}
@using (Html.BeginForm())
{
    <table class="table">
        <tr>
            <th>UserName</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Remove</th>

        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.UserName)</td>
                <td>@Html.DisplayFor(modelItem => item.Fname)</td>
                <td>@Html.DisplayFor(modelItem => item.Lname)</td>
                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                <td>
                    <input type="checkbox" name="Select" value="@item.auId" />
                </td>
            </tr>
        }
        <tr>
            <td>@Html.ActionLink("Add User", "AddUser/" + @groupId, "Groups", null, null)</td>
            <td></td>
            <td></td>
            <td></td>
            <td><input type="submit" value="Remove theese users" /></td>
        </tr>
    </table>

}

LexiconLMS/LexiconLMS/Views/Groups/Edit.cshtml
@model LexiconLMS.Models.Group

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScheduleId, "ScheduleId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ScheduleId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ScheduleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LexiconLMS/LexiconLMS/Views/Groups/Index.cshtml
@model IEnumerable<LexiconLMS.Models.Group>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <h4>Class name</h4>
        </th>
        <th>
            <h4>Schedule</h4>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.GroupName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.schedule.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>